"""Assertion: this content was generated by AI (C2PA c2pa.ai_generated)."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import ClassVar

from pqc_content_provenance.assertions.base import Assertion


@dataclass
class AIGeneratedAssertion(Assertion):
    """C2PA-compatible assertion that this content was AI-generated."""

    label: ClassVar[str] = "c2pa.ai_generated"

    model_name: str = ""                        # e.g. "Llama-3-8B-Instruct"
    model_version: str = ""                     # e.g. "1.0"
    model_did: str = ""                         # e.g. "did:pqaid:..." for this model's signer
    generator_type: str = "text"                # text | image | audio | video | multimodal
    human_edited: bool = False                  # was it post-edited by a human?
    generation_params: dict = field(default_factory=dict)  # temperature, top_p, seed, etc.
