name = "quantmrkt"
main = "./dist/_worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "quantamrkt.com"
custom_domain = true

[[routes]]
pattern = "www.quantamrkt.com"
custom_domain = true

[assets]
directory = "./dist"

[vars]
PUBLIC_SITE_URL = "https://quantamrkt.com"
GITHUB_CLIENT_ID = ""

# Secrets (set via `wrangler secret put`):
# GITHUB_CLIENT_SECRET
# SESSION_SECRET
